// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/painb0w/data_processor/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// FootballAPIClient is an autogenerated mock type for the FootballAPIClient type
type FootballAPIClient struct {
	mock.Mock
}

// GetPlayerByID provides a mock function with given fields: ctx, id
func (_m *FootballAPIClient) GetPlayerByID(ctx context.Context, id int) (*models.FootballAPIPlayerInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerByID")
	}

	var r0 *models.FootballAPIPlayerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.FootballAPIPlayerInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.FootballAPIPlayerInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FootballAPIPlayerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerByName provides a mock function with given fields: ctx, name
func (_m *FootballAPIClient) GetPlayerByName(ctx context.Context, name string) ([]models.FootballAPIPlayerInfo, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerByName")
	}

	var r0 []models.FootballAPIPlayerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.FootballAPIPlayerInfo, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.FootballAPIPlayerInfo); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FootballAPIPlayerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerStatsByPosition provides a mock function with given fields: ctx, id, pos
func (_m *FootballAPIClient) GetPlayerStatsByPosition(ctx context.Context, id int, pos string) (interface{}, error) {
	ret := _m.Called(ctx, id, pos)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStatsByPosition")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (interface{}, error)); ok {
		return rf(ctx, id, pos)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) interface{}); ok {
		r0 = rf(ctx, id, pos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, id, pos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFootballAPIClient creates a new instance of FootballAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFootballAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *FootballAPIClient {
	mock := &FootballAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
