// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mongostorage "github.com/painb0w/data_processor/internal/storage/mongostorage"
	mock "github.com/stretchr/testify/mock"
)

// PlayerStorage is an autogenerated mock type for the PlayerStorage type
type PlayerStorage struct {
	mock.Mock
}

// GetAllTrackedPlayerIDs provides a mock function with given fields: ctx
func (_m *PlayerStorage) GetAllTrackedPlayerIDs(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTrackedPlayerIDs")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlayerStatsByID provides a mock function with given fields: ctx, playerID
func (_m *PlayerStorage) GetPlayerStatsByID(ctx context.Context, playerID int) (*mongostorage.PlayerStats, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStatsByID")
	}

	var r0 *mongostorage.PlayerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*mongostorage.PlayerStats, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *mongostorage.PlayerStats); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongostorage.PlayerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertPlayerStats provides a mock function with given fields: ctx, snapshot
func (_m *PlayerStorage) UpsertPlayerStats(ctx context.Context, snapshot *mongostorage.PlayerStats) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPlayerStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *mongostorage.PlayerStats) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlayerStorage creates a new instance of PlayerStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerStorage {
	mock := &PlayerStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
