// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/painb0w/data_processor/internal/pb/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PlayerCache is an autogenerated mock type for the PlayerCache type
type PlayerCache struct {
	mock.Mock
}

// GetPlayerInfoByName provides a mock function with given fields: ctx, name
func (_m *PlayerCache) GetPlayerInfoByName(ctx context.Context, name string) ([]*models.PlayerInfo, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerInfoByName")
	}

	var r0 []*models.PlayerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.PlayerInfo, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.PlayerInfo); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PlayerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPlayerInfoByName provides a mock function with given fields: ctx, name, players, ttl
func (_m *PlayerCache) SetPlayerInfoByName(ctx context.Context, name string, players []*models.PlayerInfo, ttl time.Duration) error {
	ret := _m.Called(ctx, name, players, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetPlayerInfoByName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*models.PlayerInfo, time.Duration) error); ok {
		r0 = rf(ctx, name, players, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlayerCache creates a new instance of PlayerCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerCache {
	mock := &PlayerCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
