// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StatsProducer is an autogenerated mock type for the StatsProducer type
type StatsProducer struct {
	mock.Mock
}

// ProduceStatsUpdate provides a mock function with given fields: ctx, playerID
func (_m *StatsProducer) ProduceStatsUpdate(ctx context.Context, playerID int) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for ProduceStatsUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStatsProducer creates a new instance of StatsProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsProducer {
	mock := &StatsProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
