// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/player_stats.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Stats         [][]byte               `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStats) Reset() {
	*x = PlayerStats{}
	mi := &file_models_player_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStats) ProtoMessage() {}

func (x *PlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStats.ProtoReflect.Descriptor instead.
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return file_models_player_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerStats) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerStats) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *PlayerStats) GetStats() [][]byte {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *PlayerStats) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AttackerStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Gamesplayed     int32                  `protobuf:"varint,1,opt,name=gamesplayed,proto3" json:"gamesplayed,omitempty"`
	Shots           int32                  `protobuf:"varint,2,opt,name=shots,proto3" json:"shots,omitempty"`
	Goals           int32                  `protobuf:"varint,3,opt,name=goals,proto3" json:"goals,omitempty"`
	Assists         int32                  `protobuf:"varint,4,opt,name=assists,proto3" json:"assists,omitempty"`
	Dribbles        int32                  `protobuf:"varint,5,opt,name=dribbles,proto3" json:"dribbles,omitempty"`
	Successdribbles int32                  `protobuf:"varint,6,opt,name=successdribbles,proto3" json:"successdribbles,omitempty"`
	Foulsdrawn      int32                  `protobuf:"varint,7,opt,name=foulsdrawn,proto3" json:"foulsdrawn,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackerStats) Reset() {
	*x = AttackerStats{}
	mi := &file_models_player_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackerStats) ProtoMessage() {}

func (x *AttackerStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackerStats.ProtoReflect.Descriptor instead.
func (*AttackerStats) Descriptor() ([]byte, []int) {
	return file_models_player_stats_proto_rawDescGZIP(), []int{1}
}

func (x *AttackerStats) GetGamesplayed() int32 {
	if x != nil {
		return x.Gamesplayed
	}
	return 0
}

func (x *AttackerStats) GetShots() int32 {
	if x != nil {
		return x.Shots
	}
	return 0
}

func (x *AttackerStats) GetGoals() int32 {
	if x != nil {
		return x.Goals
	}
	return 0
}

func (x *AttackerStats) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *AttackerStats) GetDribbles() int32 {
	if x != nil {
		return x.Dribbles
	}
	return 0
}

func (x *AttackerStats) GetSuccessdribbles() int32 {
	if x != nil {
		return x.Successdribbles
	}
	return 0
}

func (x *AttackerStats) GetFoulsdrawn() int32 {
	if x != nil {
		return x.Foulsdrawn
	}
	return 0
}

type MidfielderStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gamesplayed   int32                  `protobuf:"varint,1,opt,name=gamesplayed,proto3" json:"gamesplayed,omitempty"`
	Passes        int32                  `protobuf:"varint,2,opt,name=passes,proto3" json:"passes,omitempty"`
	Keypasses     int32                  `protobuf:"varint,3,opt,name=keypasses,proto3" json:"keypasses,omitempty"`
	Assists       int32                  `protobuf:"varint,4,opt,name=assists,proto3" json:"assists,omitempty"`
	Tackles       int32                  `protobuf:"varint,5,opt,name=tackles,proto3" json:"tackles,omitempty"`
	Dribbles      int32                  `protobuf:"varint,6,opt,name=dribbles,proto3" json:"dribbles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MidfielderStats) Reset() {
	*x = MidfielderStats{}
	mi := &file_models_player_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MidfielderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MidfielderStats) ProtoMessage() {}

func (x *MidfielderStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MidfielderStats.ProtoReflect.Descriptor instead.
func (*MidfielderStats) Descriptor() ([]byte, []int) {
	return file_models_player_stats_proto_rawDescGZIP(), []int{2}
}

func (x *MidfielderStats) GetGamesplayed() int32 {
	if x != nil {
		return x.Gamesplayed
	}
	return 0
}

func (x *MidfielderStats) GetPasses() int32 {
	if x != nil {
		return x.Passes
	}
	return 0
}

func (x *MidfielderStats) GetKeypasses() int32 {
	if x != nil {
		return x.Keypasses
	}
	return 0
}

func (x *MidfielderStats) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *MidfielderStats) GetTackles() int32 {
	if x != nil {
		return x.Tackles
	}
	return 0
}

func (x *MidfielderStats) GetDribbles() int32 {
	if x != nil {
		return x.Dribbles
	}
	return 0
}

type DefenderStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gamesplayed   int32                  `protobuf:"varint,1,opt,name=gamesplayed,proto3" json:"gamesplayed,omitempty"`
	Tackles       int32                  `protobuf:"varint,2,opt,name=tackles,proto3" json:"tackles,omitempty"`
	Interceptions int32                  `protobuf:"varint,3,opt,name=interceptions,proto3" json:"interceptions,omitempty"`
	Blocks        int32                  `protobuf:"varint,4,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Foulscommited int32                  `protobuf:"varint,5,opt,name=foulscommited,proto3" json:"foulscommited,omitempty"`
	Duelswon      int32                  `protobuf:"varint,6,opt,name=duelswon,proto3" json:"duelswon,omitempty"`
	Duels         int32                  `protobuf:"varint,7,opt,name=duels,proto3" json:"duels,omitempty"`
	Yellowcards   int32                  `protobuf:"varint,8,opt,name=yellowcards,proto3" json:"yellowcards,omitempty"`
	Redcards      int32                  `protobuf:"varint,9,opt,name=redcards,proto3" json:"redcards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefenderStats) Reset() {
	*x = DefenderStats{}
	mi := &file_models_player_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefenderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefenderStats) ProtoMessage() {}

func (x *DefenderStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefenderStats.ProtoReflect.Descriptor instead.
func (*DefenderStats) Descriptor() ([]byte, []int) {
	return file_models_player_stats_proto_rawDescGZIP(), []int{3}
}

func (x *DefenderStats) GetGamesplayed() int32 {
	if x != nil {
		return x.Gamesplayed
	}
	return 0
}

func (x *DefenderStats) GetTackles() int32 {
	if x != nil {
		return x.Tackles
	}
	return 0
}

func (x *DefenderStats) GetInterceptions() int32 {
	if x != nil {
		return x.Interceptions
	}
	return 0
}

func (x *DefenderStats) GetBlocks() int32 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *DefenderStats) GetFoulscommited() int32 {
	if x != nil {
		return x.Foulscommited
	}
	return 0
}

func (x *DefenderStats) GetDuelswon() int32 {
	if x != nil {
		return x.Duelswon
	}
	return 0
}

func (x *DefenderStats) GetDuels() int32 {
	if x != nil {
		return x.Duels
	}
	return 0
}

func (x *DefenderStats) GetYellowcards() int32 {
	if x != nil {
		return x.Yellowcards
	}
	return 0
}

func (x *DefenderStats) GetRedcards() int32 {
	if x != nil {
		return x.Redcards
	}
	return 0
}

type GoalkeeperStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gamesplayed    int32                  `protobuf:"varint,1,opt,name=gamesplayed,proto3" json:"gamesplayed,omitempty"`
	Conceded       int32                  `protobuf:"varint,2,opt,name=conceded,proto3" json:"conceded,omitempty"`
	Saves          int32                  `protobuf:"varint,3,opt,name=saves,proto3" json:"saves,omitempty"`
	Penalties      int32                  `protobuf:"varint,4,opt,name=penalties,proto3" json:"penalties,omitempty"`
	Penaltiessaved int32                  `protobuf:"varint,5,opt,name=penaltiessaved,proto3" json:"penaltiessaved,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoalkeeperStats) Reset() {
	*x = GoalkeeperStats{}
	mi := &file_models_player_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalkeeperStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalkeeperStats) ProtoMessage() {}

func (x *GoalkeeperStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalkeeperStats.ProtoReflect.Descriptor instead.
func (*GoalkeeperStats) Descriptor() ([]byte, []int) {
	return file_models_player_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GoalkeeperStats) GetGamesplayed() int32 {
	if x != nil {
		return x.Gamesplayed
	}
	return 0
}

func (x *GoalkeeperStats) GetConceded() int32 {
	if x != nil {
		return x.Conceded
	}
	return 0
}

func (x *GoalkeeperStats) GetSaves() int32 {
	if x != nil {
		return x.Saves
	}
	return 0
}

func (x *GoalkeeperStats) GetPenalties() int32 {
	if x != nil {
		return x.Penalties
	}
	return 0
}

func (x *GoalkeeperStats) GetPenaltiessaved() int32 {
	if x != nil {
		return x.Penaltiessaved
	}
	return 0
}

var File_models_player_stats_proto protoreflect.FileDescriptor

const file_models_player_stats_proto_rawDesc = "" +
	"\n" +
	"\x19models/player_stats.proto\x12\tmodels.v1\"\x82\x01\n" +
	"\vPlayerStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x14\n" +
	"\x05stats\x18\x04 \x03(\fR\x05stats\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xdd\x01\n" +
	"\rAttackerStats\x12 \n" +
	"\vgamesplayed\x18\x01 \x01(\x05R\vgamesplayed\x12\x14\n" +
	"\x05shots\x18\x02 \x01(\x05R\x05shots\x12\x14\n" +
	"\x05goals\x18\x03 \x01(\x05R\x05goals\x12\x18\n" +
	"\aassists\x18\x04 \x01(\x05R\aassists\x12\x1a\n" +
	"\bdribbles\x18\x05 \x01(\x05R\bdribbles\x12(\n" +
	"\x0fsuccessdribbles\x18\x06 \x01(\x05R\x0fsuccessdribbles\x12\x1e\n" +
	"\n" +
	"foulsdrawn\x18\a \x01(\x05R\n" +
	"foulsdrawn\"\xb9\x01\n" +
	"\x0fMidfielderStats\x12 \n" +
	"\vgamesplayed\x18\x01 \x01(\x05R\vgamesplayed\x12\x16\n" +
	"\x06passes\x18\x02 \x01(\x05R\x06passes\x12\x1c\n" +
	"\tkeypasses\x18\x03 \x01(\x05R\tkeypasses\x12\x18\n" +
	"\aassists\x18\x04 \x01(\x05R\aassists\x12\x18\n" +
	"\atackles\x18\x05 \x01(\x05R\atackles\x12\x1a\n" +
	"\bdribbles\x18\x06 \x01(\x05R\bdribbles\"\x9f\x02\n" +
	"\rDefenderStats\x12 \n" +
	"\vgamesplayed\x18\x01 \x01(\x05R\vgamesplayed\x12\x18\n" +
	"\atackles\x18\x02 \x01(\x05R\atackles\x12$\n" +
	"\rinterceptions\x18\x03 \x01(\x05R\rinterceptions\x12\x16\n" +
	"\x06blocks\x18\x04 \x01(\x05R\x06blocks\x12$\n" +
	"\rfoulscommited\x18\x05 \x01(\x05R\rfoulscommited\x12\x1a\n" +
	"\bduelswon\x18\x06 \x01(\x05R\bduelswon\x12\x14\n" +
	"\x05duels\x18\a \x01(\x05R\x05duels\x12 \n" +
	"\vyellowcards\x18\b \x01(\x05R\vyellowcards\x12\x1a\n" +
	"\bredcards\x18\t \x01(\x05R\bredcards\"\xab\x01\n" +
	"\x0fGoalkeeperStats\x12 \n" +
	"\vgamesplayed\x18\x01 \x01(\x05R\vgamesplayed\x12\x1a\n" +
	"\bconceded\x18\x02 \x01(\x05R\bconceded\x12\x14\n" +
	"\x05saves\x18\x03 \x01(\x05R\x05saves\x12\x1c\n" +
	"\tpenalties\x18\x04 \x01(\x05R\tpenalties\x12&\n" +
	"\x0epenaltiessaved\x18\x05 \x01(\x05R\x0epenaltiessavedB6Z4github.com/painb0w/data_processor/internal/pb/modelsb\x06proto3"

var (
	file_models_player_stats_proto_rawDescOnce sync.Once
	file_models_player_stats_proto_rawDescData []byte
)

func file_models_player_stats_proto_rawDescGZIP() []byte {
	file_models_player_stats_proto_rawDescOnce.Do(func() {
		file_models_player_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_player_stats_proto_rawDesc), len(file_models_player_stats_proto_rawDesc)))
	})
	return file_models_player_stats_proto_rawDescData
}

var file_models_player_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_player_stats_proto_goTypes = []any{
	(*PlayerStats)(nil),     // 0: models.v1.PlayerStats
	(*AttackerStats)(nil),   // 1: models.v1.AttackerStats
	(*MidfielderStats)(nil), // 2: models.v1.MidfielderStats
	(*DefenderStats)(nil),   // 3: models.v1.DefenderStats
	(*GoalkeeperStats)(nil), // 4: models.v1.GoalkeeperStats
}
var file_models_player_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_player_stats_proto_init() }
func file_models_player_stats_proto_init() {
	if File_models_player_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_player_stats_proto_rawDesc), len(file_models_player_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_player_stats_proto_goTypes,
		DependencyIndexes: file_models_player_stats_proto_depIdxs,
		MessageInfos:      file_models_player_stats_proto_msgTypes,
	}.Build()
	File_models_player_stats_proto = out.File
	file_models_player_stats_proto_goTypes = nil
	file_models_player_stats_proto_depIdxs = nil
}
