// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/player_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Nationality   string                 `protobuf:"bytes,4,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Height        string                 `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight        string                 `protobuf:"bytes,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Photo         string                 `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
	Position      string                 `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_models_player_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_models_player_model_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PlayerInfo) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *PlayerInfo) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *PlayerInfo) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *PlayerInfo) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *PlayerInfo) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_models_player_model_proto protoreflect.FileDescriptor

const file_models_player_model_proto_rawDesc = "" +
	"\n" +
	"\x19models/player_model.proto\x12\tmodels.v1\"\xc6\x01\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12 \n" +
	"\vnationality\x18\x04 \x01(\tR\vnationality\x12\x16\n" +
	"\x06height\x18\x05 \x01(\tR\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\tR\x06weight\x12\x14\n" +
	"\x05photo\x18\a \x01(\tR\x05photo\x12\x1a\n" +
	"\bposition\x18\b \x01(\tR\bpositionB6Z4github.com/painb0w/data_processor/internal/pb/modelsb\x06proto3"

var (
	file_models_player_model_proto_rawDescOnce sync.Once
	file_models_player_model_proto_rawDescData []byte
)

func file_models_player_model_proto_rawDescGZIP() []byte {
	file_models_player_model_proto_rawDescOnce.Do(func() {
		file_models_player_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_player_model_proto_rawDesc), len(file_models_player_model_proto_rawDesc)))
	})
	return file_models_player_model_proto_rawDescData
}

var file_models_player_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_player_model_proto_goTypes = []any{
	(*PlayerInfo)(nil), // 0: models.v1.PlayerInfo
}
var file_models_player_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_player_model_proto_init() }
func file_models_player_model_proto_init() {
	if File_models_player_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_player_model_proto_rawDesc), len(file_models_player_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_player_model_proto_goTypes,
		DependencyIndexes: file_models_player_model_proto_depIdxs,
		MessageInfos:      file_models_player_model_proto_msgTypes,
	}.Build()
	File_models_player_model_proto = out.File
	file_models_player_model_proto_goTypes = nil
	file_models_player_model_proto_depIdxs = nil
}
