// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: players_api/players.proto

package players_api

import (
	context "context"
	models "github.com/painb0w/data_processor/internal/pb/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayersService_GetPlayerInfoByName_FullMethodName = "/players.api.v1.PlayersService/GetPlayerInfoByName"
	PlayersService_GetPlayerStatsByID_FullMethodName  = "/players.api.v1.PlayersService/GetPlayerStatsByID"
)

// PlayersServiceClient is the client API for PlayersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayersServiceClient interface {
	GetPlayerInfoByName(ctx context.Context, in *GetPlayerInfoByNameRequest, opts ...grpc.CallOption) (*GetPlayerInfoByNameResponse, error)
	GetPlayerStatsByID(ctx context.Context, in *GetPlayerStatsByIDRequest, opts ...grpc.CallOption) (*models.PlayerStats, error)
}

type playersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayersServiceClient(cc grpc.ClientConnInterface) PlayersServiceClient {
	return &playersServiceClient{cc}
}

func (c *playersServiceClient) GetPlayerInfoByName(ctx context.Context, in *GetPlayerInfoByNameRequest, opts ...grpc.CallOption) (*GetPlayerInfoByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerInfoByNameResponse)
	err := c.cc.Invoke(ctx, PlayersService_GetPlayerInfoByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playersServiceClient) GetPlayerStatsByID(ctx context.Context, in *GetPlayerStatsByIDRequest, opts ...grpc.CallOption) (*models.PlayerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(models.PlayerStats)
	err := c.cc.Invoke(ctx, PlayersService_GetPlayerStatsByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayersServiceServer is the server API for PlayersService service.
// All implementations must embed UnimplementedPlayersServiceServer
// for forward compatibility.
type PlayersServiceServer interface {
	GetPlayerInfoByName(context.Context, *GetPlayerInfoByNameRequest) (*GetPlayerInfoByNameResponse, error)
	GetPlayerStatsByID(context.Context, *GetPlayerStatsByIDRequest) (*models.PlayerStats, error)
	mustEmbedUnimplementedPlayersServiceServer()
}

// UnimplementedPlayersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayersServiceServer struct{}

func (UnimplementedPlayersServiceServer) GetPlayerInfoByName(context.Context, *GetPlayerInfoByNameRequest) (*GetPlayerInfoByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerInfoByName not implemented")
}
func (UnimplementedPlayersServiceServer) GetPlayerStatsByID(context.Context, *GetPlayerStatsByIDRequest) (*models.PlayerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerStatsByID not implemented")
}
func (UnimplementedPlayersServiceServer) mustEmbedUnimplementedPlayersServiceServer() {}
func (UnimplementedPlayersServiceServer) testEmbeddedByValue()                        {}

// UnsafePlayersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayersServiceServer will
// result in compilation errors.
type UnsafePlayersServiceServer interface {
	mustEmbedUnimplementedPlayersServiceServer()
}

func RegisterPlayersServiceServer(s grpc.ServiceRegistrar, srv PlayersServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayersService_ServiceDesc, srv)
}

func _PlayersService_GetPlayerInfoByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).GetPlayerInfoByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_GetPlayerInfoByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).GetPlayerInfoByName(ctx, req.(*GetPlayerInfoByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayersService_GetPlayerStatsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatsByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).GetPlayerStatsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_GetPlayerStatsByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).GetPlayerStatsByID(ctx, req.(*GetPlayerStatsByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayersService_ServiceDesc is the grpc.ServiceDesc for PlayersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "players.api.v1.PlayersService",
	HandlerType: (*PlayersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerInfoByName",
			Handler:    _PlayersService_GetPlayerInfoByName_Handler,
		},
		{
			MethodName: "GetPlayerStatsByID",
			Handler:    _PlayersService_GetPlayerStatsByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "players_api/players.proto",
}
