// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: players_api/players.proto

package players_api

import (
	models "github.com/painb0w/data_processor/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerInfoByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoByNameRequest) Reset() {
	*x = GetPlayerInfoByNameRequest{}
	mi := &file_players_api_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoByNameRequest) ProtoMessage() {}

func (x *GetPlayerInfoByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoByNameRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerInfoByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayerInfoByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfos   []*models.PlayerInfo   `protobuf:"bytes,1,rep,name=playerInfos,proto3" json:"playerInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoByNameResponse) Reset() {
	*x = GetPlayerInfoByNameResponse{}
	mi := &file_players_api_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoByNameResponse) ProtoMessage() {}

func (x *GetPlayerInfoByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoByNameResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoByNameResponse) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerInfoByNameResponse) GetPlayerInfos() []*models.PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type GetPlayerStatsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatsByIDRequest) Reset() {
	*x = GetPlayerStatsByIDRequest{}
	mi := &file_players_api_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsByIDRequest) ProtoMessage() {}

func (x *GetPlayerStatsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsByIDRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerStatsByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlayerStatsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*models.PlayerStats  `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatsByIDsResponse) Reset() {
	*x = GetPlayerStatsByIDsResponse{}
	mi := &file_players_api_players_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsByIDsResponse) ProtoMessage() {}

func (x *GetPlayerStatsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerStatsByIDsResponse) GetStats() []*models.PlayerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_players_api_players_proto protoreflect.FileDescriptor

const file_players_api_players_proto_rawDesc = "" +
	"\n" +
	"\x19players_api/players.proto\x12\x0eplayers.api.v1\x1a\x19models/player_model.proto\x1a\x19models/player_stats.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x1aGetPlayerInfoByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x1bGetPlayerInfoByNameResponse\x127\n" +
	"\vplayerInfos\x18\x01 \x03(\v2\x15.models.v1.PlayerInfoR\vplayerInfos\"+\n" +
	"\x19GetPlayerStatsByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"K\n" +
	"\x1bGetPlayerStatsByIDsResponse\x12,\n" +
	"\x05stats\x18\x01 \x03(\v2\x16.models.v1.PlayerStatsR\x05stats2\x99\x02\n" +
	"\x0ePlayersService\x12\x92\x01\n" +
	"\x13GetPlayerInfoByName\x12*.players.api.v1.GetPlayerInfoByNameRequest\x1a+.players.api.v1.GetPlayerInfoByNameResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/playerInfo/get-by-name\x12r\n" +
	"\x12GetPlayerStatsByID\x12).players.api.v1.GetPlayerStatsByIDRequest\x1a\x16.models.v1.PlayerStats\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/playerStats/{id}B;Z9github.com/painb0w/data_processor/internal/pb/players_apib\x06proto3"

var (
	file_players_api_players_proto_rawDescOnce sync.Once
	file_players_api_players_proto_rawDescData []byte
)

func file_players_api_players_proto_rawDescGZIP() []byte {
	file_players_api_players_proto_rawDescOnce.Do(func() {
		file_players_api_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)))
	})
	return file_players_api_players_proto_rawDescData
}

var file_players_api_players_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_players_api_players_proto_goTypes = []any{
	(*GetPlayerInfoByNameRequest)(nil),  // 0: players.api.v1.GetPlayerInfoByNameRequest
	(*GetPlayerInfoByNameResponse)(nil), // 1: players.api.v1.GetPlayerInfoByNameResponse
	(*GetPlayerStatsByIDRequest)(nil),   // 2: players.api.v1.GetPlayerStatsByIDRequest
	(*GetPlayerStatsByIDsResponse)(nil), // 3: players.api.v1.GetPlayerStatsByIDsResponse
	(*models.PlayerInfo)(nil),           // 4: models.v1.PlayerInfo
	(*models.PlayerStats)(nil),          // 5: models.v1.PlayerStats
}
var file_players_api_players_proto_depIdxs = []int32{
	4, // 0: players.api.v1.GetPlayerInfoByNameResponse.playerInfos:type_name -> models.v1.PlayerInfo
	5, // 1: players.api.v1.GetPlayerStatsByIDsResponse.stats:type_name -> models.v1.PlayerStats
	0, // 2: players.api.v1.PlayersService.GetPlayerInfoByName:input_type -> players.api.v1.GetPlayerInfoByNameRequest
	2, // 3: players.api.v1.PlayersService.GetPlayerStatsByID:input_type -> players.api.v1.GetPlayerStatsByIDRequest
	1, // 4: players.api.v1.PlayersService.GetPlayerInfoByName:output_type -> players.api.v1.GetPlayerInfoByNameResponse
	5, // 5: players.api.v1.PlayersService.GetPlayerStatsByID:output_type -> models.v1.PlayerStats
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_players_api_players_proto_init() }
func file_players_api_players_proto_init() {
	if File_players_api_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_players_api_players_proto_goTypes,
		DependencyIndexes: file_players_api_players_proto_depIdxs,
		MessageInfos:      file_players_api_players_proto_msgTypes,
	}.Build()
	File_players_api_players_proto = out.File
	file_players_api_players_proto_goTypes = nil
	file_players_api_players_proto_depIdxs = nil
}
